// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://invtiwfurexgcfggmuny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludnRpd2Z1cmV4Z2NmZ2dtdW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDQzMzksImV4cCI6MjA1ODQ4MDMzOX0.PnwLR6pJ97e8pMaautBSbVy8hZWPTz-kcm0elkmKgAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);